
# 로그인 계정
#- id : user1 password : 1q2w3e4r!
#- id : user2 password : 1q2w3e4r!
#- id : user3 password : 1q2w3e4r!
#- id : user4 password : 1q2w3e4r!


# STEP 1. 로그인 API 호출 후 쿠키에서 SON_SESSION_ID 를 긁어서 계속 사용합니다 (호출 시 계속 바뀝니다.)
# ex) SON_SESSION_ID=e4cb946e-5e9a-42d7-9e08-1717ad9bdfb4
POST http://localhost:8080/member/login/check
Content-Type: application/json

{
  "loginId": "user2",
  "loginPassword": "1q2w3e4r!"
}

###
# STEP 2. 문서를 생성 합니다.
POST http://localhost:8080/document/create
Cookie: SON_SESSION_ID=c83b76e8-77b8-4cbf-880c-95aed16c1092
Content-Type: application/json

{
  "title": "테스트입니다",
  "documentType": "VACATION_REPORT",
  "contents": "휴가신청서 본문 입니다.",
  "documentApproval": null,
  "documentApprovalGroupDto": [
    {
      "approvalMemberId": 1,
      "sort": 1
    },
    {
      "approvalMemberId": 2,
      "sort": 2
    }
  ]
}

###
# STEP 3. 문서 단 건을 조회 합니다.
GET http://localhost:8080/document/6
Cookie: SON_SESSION_ID=c93b2d5a-71fd-4608-a45a-3b019440fac9
Content-Type: application/json

###
# STEP 3. 문서 전체를 조회 합니다.
GET http://localhost:8080/document?documentSearchType=OUTBOX
Cookie: SON_SESSION_ID=e2e94682-740f-4663-82cd-2b6f01b5776e
Content-Type: application/json

###
# STEP 3. 문서상태가 임시 저장 상태일 때 계속 저장 가능합니다
PUT http://localhost:8080/document/update
Cookie: SON_SESSION_ID=41b17169-956f-4d0d-9e41-bde8ed229cd7
Content-Type: application/json

{
  "id": 1,
  "title": "테스트입니다!!!!!!",
  "documentType": "VACATION_REPORT",
  "contents": "휴가신청서 본문 입니다. 연봉도 많이 올려주세요",
  "documentApproval": null,
  "documentApprovalGroupDto": [
    {
      "approvalMemberId": 2,
      "sort": 1
    },
    {
      "approvalMemberId": 1,
      "sort": 2
    }
  ]
}

###
# STEP 4. 문서를 결재 상신합니다.
PUT http://localhost:8080/document/approval
Cookie: SON_SESSION_ID=7d7cdf6f-dfbb-4bf0-a7fe-9098e9b4fd08
Content-Type: application/json

{
  "id": 6,
  "title": "테스트입니다",
  "documentType": "VACATION_REPORT",
  "contents": "휴가신청서 본문 입니다.ㅋㅋ",
  "documentApproval": null,
  "documentApprovalGroupDto": [
    {
      "approvalMemberId": 1,
      "sort": 1
    },
    {
      "approvalMemberId": 1,
      "sort": 2
    }
  ]
}

###
# STEP 5.1. 결재자로 등록된 해당 id 문서 결재 승인할 수 있습니다. (아래 id에 문서 번호를 넣어주세요.)
# /document/{{id}}/approval/approve

PUT http://localhost:8080/document/6/approval/approve
Cookie: SON_SESSION_ID=b61d5c4f-f834-4de3-b382-e4bccf2119a5
Content-Type: application/json

###
# STEP 5.2. 결재자로 등록된 해당 id 문서 결재 반려할 수 있습니다. (아래 id에 문서 번호를 넣어주세요.)
# /document/{{id}}/approval/reject
PUT http://localhost:8080/document/6/approval/reject
Cookie: SON_SESSION_ID=64c9426f-46f7-4b09-8f39-b68ab971c32d
Content-Type: application/json

